BugTracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings
from app.views import BugView, ProfileView, singleBugView, HomeView, CommentsView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('bugs/', BugView.as_view(), name='bugs-view'),
    path('bugs/<int:pk>', singleBugView.as_view(), name='single-bug'),
    path('bugs/<int:pk>/comment', CommentsView.as_view(), name='comments'),
    path('profile/', ProfileView.as_view(), name='profile-view'),
    path('', HomeView.as_view(), name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

app/forms.py
from django import forms
from .models import Profile
class BugForm(forms.Form):
    PRIORITIES = (
        ('High', 'High'),
        ('Medium', 'Medium'),
        ('Low', 'Low'),
    )

    title = forms.CharField(
        widget=forms.TextInput(
            attrs={'class':'form-control'}),
        label='Title', max_length=80)
    description = forms.CharField(
        widget=forms.Textarea(
            attrs={'class': 'form-control'}),
        label='Description', max_length=10000)
    priority = forms.ChoiceField(
        widget=forms.Select(
            attrs={'class': 'form-control'}), 
        choices=PRIORITIES)

class CommentForm(forms.Form):
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'class': 'form-control', 'rows': 2}),
        label='Comment', max_length=512)
    
# class ProfileForm(forms.Form):
#     bio = forms.CharField(
#         widget=forms.TextInput(
#             attrs={'class':'form-control'}),
#         label='Bio', max_length=512)
#     image = forms.ImageField(required=False)

# class UserForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'image')
        widgets = {
            'bio': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
        }

templates/bugs/bugs.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% block content %}
{% if user.is_authenticated %}
    <div class="container">
        <div class="row mt-4">
            <h2>Submit a new bug</h2>
        </div>
        <hr class="m-4">
    </div>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group row">
                <label for="titleInput" class="col-form-label col-sm-2">Title</label>
                    <div class="col-sm-10 ">
                        {{ form.title }}
                        <small id="titleHelp" class="form-text text-muted">A title for your entry</small>
                    </div>
            </div>
            <div class="form-group row">
                <label for="descriptionInput" class="col-form-label col-sm-2">Description</label>
                    <div class="col-sm-10">
                        {{ form.description }}
                        <small id="descriptionHelp" class="form-text text-muted">Please provide information about the problem you encountered</small>
                    </div>
            </div>
            <div class="form-group row">
                <label for="descriptionInput" class="col-form-label col-sm-2">Priority</label>
                <div class="col-sm-10">
                        {{ form.priority }}
                    <small id="descriptionHelp" class="form-text text-muted">Please provide priority level</small>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10 offset-sm-2">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>
        <div class="container py-4">
            <div class="row mt-4">
                <h2>Bug list</h2>
            </div>
        </div>
        <div class="card border scroll">
            <div class="card-body">
                {% for bug in bugs %}
                <div class="list-group">
                    <a href="/bugs/{{ bug.id }}" class="list-group-item list-group-item-action  {% if bug.fixed %} bg-success {% else %} bg-light {% endif %}"> {{ bug.title }} </a>
                </div>
                {% endfor %}
            </div>
        </div>

{% else %}
    <p>You are not logged in</p>
    <a href="{% url 'login' %}">Login</a>
    <p>Not registered yet? Sign up <a href="/accounts/signup/">here</a></p>
{% endif %}
{% endblock %}

templates/bugs/bugsTest.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}
    <div class="row">
        {{form.as_p}}
    </div>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Login</a>
  <p>Not registered yet? Sign up <a href="/accounts/signup/">here</a></p>
{% endif %}
{% endblock %}

templates/bugs/modal.html
        <!-- Modal -->
		<div class="modal fade bd-example-modal-lg" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-lg" role="document">
			<div class="modal-content">
				<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Edit your submitted bug</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				</div>
				<div class="modal-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label for="titleInput" class="col-form-label col-sm-2">Title</label>
                                <div class="col-sm-10 ">
                                    <input type="text" name="title" class="form-control" maxlength="80" required="" id="id_title" value="{{ bug.title }}">
                                    <small id="titleHelp" class="form-text text-muted">A title for your entry</small>
                                </div>
                        </div>
                        <div class="form-group row">
                            <label for="descriptionInput" class="col-form-label col-sm-2">Description</label>
                                <div class="col-sm-10">
                                    <textarea name="description" cols="40" rows="10" class="form-control" maxlength="10000" required="" id="id_description" style="height: 271px;">{{ bug.description }}</textarea>
                                    <small id="descriptionHelp" class="form-text text-muted">Please provide information about the problem you encountered</small>
                                </div>
                        </div>
                        <div class="form-group row">
                            <label for="descriptionInput" class="col-aform-label col-sm-2">Priority</label>
                            <div class="col-sm-10">
                                <select name="priority" class="form-control" id="id_priority">
                                    <option value="High">High</option>
                                    <option value="Medium">Medium</option>
                                    <option value="Low">Low</option>
                                </select>
                                <small id="descriptionHelp" class="form-text text-muted">Please provide priority level</small>
                            </div>
                        </div>
                    </form>
				</div>
				<div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button onclick="handleClick()" class="btn btn-primary">Update</button>
				</div>
			</div>
			</div>
        </div>
        <script>
            function handleClick() {
                let title = $("#id_title").val();
                let description = $("#id_description").val();
                let priority = $("#id_priority").val()
                console.log(description, title, priority);
                bugs.UpdateBug({{ bug.pk }}, title, description, priority)
            }
        </script>

templates/bugs/singleBug.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% load markdownify %}
{% block content %}
{% include 'bugs/modal.html'%}
{% if user.is_authenticated %}
		<div class="card">
			<div class="card-header">
				<h2>{{ bug.title }}</h2>
			</div>
			<div class="card-body">
				<div class="row">
					<div class="col-1 h-100 p-auto">
						<a class="btn btn-success" onclick="bugs.ScoreBug({{ bug.pk }}, 1)" role="button">&uarr;</a>
						<p class="m-2">{{ bug.score }}</p>
						<a class="btn btn-danger" onclick="bugs.ScoreBug({{ bug.pk }}, -1)" role="button">&darr;</a>
					</div>
					<div class="col-10 p-0 m-0 justify-content-between">
						<h5 class="card-title">Issue submitted by {{ bug.reported_by|title }} on {{ bug.created_at }}</h5>
						<p class="card-text">{{ bug.description|markdownify |linebreaks}}</p>
					</div>
				</div>
				<div class="border-top border-dark mt-1 pt-1 py-3 container">
					<ul class="list-inline row">
						<div class="col-6">
							<li class="list-inline-item"><em><b>Bug Priority:</b></em> {{ bug.priority }}</li>
							<li class="list-inline-item"><em><b>Bug is fixed:</b></em> {{ bug.fixed }}</li>
							<li class="list-inline-item"><em><b>Points:</b></em> {{ bug.score }}</li>
						</div>
						<div class="col">
						</div>
						 {% if user == bug.reported_by %}
						<div class="btn-group col-md-auto justify-content-end" role="group">
							<button id="btnGroupDrop1" type="button"
									class="btn btn-secondary dropdown-toggle"
									data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							⚙
							</button>
							<div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
								<button onclick="bugs.DeleteBug({{ bug.pk }})" class="btn btn-danger dropdown-item">Delete</button>
								<button id="editButton" type="button" class="btn btn-primary dropdown-item" data-toggle="modal" data-taget="#editModal">Edit</button>
								<button onclick="bugs.MarkAsFixed({{ bug.pk }}, {{ bug.fixed|lower}})" class="btn btn-primary dropdown-item">Toggle fixed</button>
							</div>
						</div>
						{% endif %}
					</ul>
				</div>
				<div>
					<div class="list-group">
						{% for comment in comments %}
						<div class="list-group-item alert alert-primary container">
							<div class="row p-0 m-0">
								<div class="col-1 h-100 p-auto">
									<a class="btn btn-success" onclick="comments.ScoreComment({{ bug.pk }}, {{ comment.pk }}, 1)" role="button">&uarr;</a>
									<p class="m-2">{{ comment.score }}</p>
									<a class="btn btn-danger" onclick="comments.ScoreComment({{ bug.pk }}, {{ comment.pk }}, -1)" role="button">&darr;</a>
								</div>
								<div class="col-11 p-0 m-0">
									<div class="d-flex w-100 justify-content-between">
										<h5 class="mb-1">{{ comment.commented_by|title }}:</h5>
										<small>{{ comment.created_at }}</small>
									</div>
									<p class="">{{ comment.message }}</p>
								</div>
								<div class="row">
									<div class="col-1"></div>
								</div>
							</div>
						</div>
						{% endfor %}
					</div>
					</div>
					<div class="card">
						<div class="card-body">
							<h5 class="card-title">Take part in the discussion:</h5>
							<form method="POST" action="{{ bug.pk }}/comment">
							{% csrf_token %}
							<div class="form-group row">
								<label for="commentInput" class="col-form-label px-2">Comment</label>
								<div class="col-10 ">
									{{ form.message }}
									<small id="titleHelp" class="form-text text-muted">Please be civil</small>
								</div>
								<div class="row align-items-end py-4 px-2 col">
									<button type="submit" class="btn btn-primary align-bottom">Comment</button>
								</div>
							</div>
							</form>
						</div>
					</div>
				</div>
		</div>
		<script>
				let editModal = $("#editModal");
				$("#editButton").click(function(){
					editModal.modal();
				})
		</script>
{% else %}
	<p>You are not logged in</p>
	<a href="{% url 'login' %}">Login</a>
	<p>Not registered yet? Sign up <a href="/accounts/signup/">here</a></p>
{% endif %}
{% endblock %}